# Generated by Django 5.0.6 on 2024-05-24 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_vendor_product_product_vendor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_category',
        ),
    ]
