# Generated by Django 5.0.6 on 2024-05-24 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_product_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_vendor',
        ),
    ]
