# Generated by Django 5.0.6 on 2024-05-24 18:20

import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_color_gallery_size_specification'),
        ('vendor', '0004_vendor_vendor_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=0, default=0.0, max_digits=20)),
                ('sub_total', models.DecimalField(decimal_places=0, default=0.0, max_digits=20)),
                ('shipping_amount', models.DecimalField(decimal_places=0, default=0.0, max_digits=20)),
                ('tax_fee', models.DecimalField(decimal_places=0, default=0.0, max_digits=20)),
                ('service_fee', models.DecimalField(decimal_places=0, default=0.0, max_digits=20)),
                ('total', models.DecimalField(decimal_places=0, default=0.0, max_digits=20)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('cart_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cart_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_total', models.DecimalField(decimal_places=0, default=0.0, max_digits=20)),
                ('shipping_amount', models.DecimalField(decimal_places=0, default=0.0, max_digits=20)),
                ('tax_fee', models.DecimalField(decimal_places=0, default=0.0, max_digits=20)),
                ('service_fee', models.DecimalField(decimal_places=0, default=0.0, max_digits=20)),
                ('total', models.DecimalField(decimal_places=0, default=0.0, max_digits=20)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('processing', 'Processing'), ('cancelled', 'Cancelled')], default='pending', max_length=100)),
                ('order_status', models.CharField(choices=[('pending', 'Pending'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='pending', max_length=100)),
                ('initial_total', models.DecimalField(decimal_places=0, default=0.0, max_digits=20)),
                ('saved', models.DecimalField(decimal_places=0, default=0.0, max_digits=20)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('oid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrtuvwxyz', length=10, max_length=20, prefix='', unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cart_order_vendor', models.ManyToManyField(blank=True, to='vendor.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='CartOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=0, default=0.0, max_digits=20)),
                ('sub_total', models.DecimalField(decimal_places=0, default=0.0, max_digits=20)),
                ('shipping_amount', models.DecimalField(decimal_places=0, default=0.0, max_digits=20)),
                ('tax_fee', models.DecimalField(decimal_places=0, default=0.0, max_digits=20)),
                ('service_fee', models.DecimalField(decimal_places=0, default=0.0, max_digits=20)),
                ('total', models.DecimalField(decimal_places=0, default=0.0, max_digits=20)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('initial_total', models.DecimalField(decimal_places=0, default=0.0, max_digits=20)),
                ('saved', models.DecimalField(decimal_places=0, default=0.0, max_digits=20)),
                ('oid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrtuvwxyz', length=10, max_length=20, prefix='', unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('item_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('item_vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.cartorder')),
            ],
        ),
    ]
