# Generated by Django 5.0.6 on 2024-05-25 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_coupon_notification_productfaq_review_whishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='specification_product',
            new_name='color_product',
        ),
        migrations.RenameField(
            model_name='size',
            old_name='specification_product',
            new_name='size_product',
        ),
    ]
