name: Checkout

on:
  push:
  issues:
    types:
      - opened

jobs:
  checkout_and_display_files:
    runs-on: ubuntu-latest
    steps:
      - name: list file before
        run: ls -a
      - uses: actions/checkout@v3
      - name: list file after
        run: ls -a
